# Generated by Django 4.1.5 on 2023-02-09 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('evt_date__gte', datetime.datetime(2023, 2, 9, 19, 51, 5, 57893))), name='Please check out the event date'),
        ),
    ]
